# Generated by Django 4.1.7 on 2023-08-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='phonenum',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
