# Generated by Django 4.1.7 on 2023-08-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='editor_address',
            field=models.CharField(default='', max_length=50),
        ),
    ]
