# Generated by Django 4.1.7 on 2023-08-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_editor_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='editor_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
