# Generated by Django 4.1.7 on 2023-08-18 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_ID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=128)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('F', 'female'), ('M', 'male')], max_length=1)),
                ('birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(choices=[('Seoul', '서울특별시'), ('Gyeonggi', '경기도'), ('Incheon', '인천광역시'), ('Gangwon', '강원도'), ('Chungbuk', '충청북도'), ('Chungnam', '충청남도'), ('Gyeongbuk', '경상북도'), ('Gyeongnam', '경상남도'), ('Jeju', '제주특별자치도'), ('Jeonbuk', '전라북도'), ('Jeonnam', '전라남도')], max_length=50)),
                ('city', models.CharField(blank=True, choices=[('Jungguo', '중구'), ('Jongrogu', '종로구'), ('Yongsangu', '용산구'), ('Seongdonggu', '성동구'), ('Gwangjingu', '광진구'), ('Dongdaemungu', '동대문구'), ('Jungranggu', '중랑구'), ('Seongbukgu', '성북구'), ('Gangbukgu', '강북구'), ('Dobonggu', '도봉구'), ('Nowongu', '노원구'), ('Eunpyeonggu', '은평구'), ('Seodaemungu', '서대문구'), ('Mapogu', '마포구'), ('Yangcheongu', '양천구'), ('Gangseogu', '강서구'), ('Gurogu', '구로구'), ('Geumcheongu', '금천구'), ('Uijeongbu', '의정부시'), ('Goyang', '고양시'), ('Yangju', '양주시'), ('Dongducheon', '동두천시'), ('Guri', '구리시'), ('Namyangju', '남양주시'), ('Paju', '파주시')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=10, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_address', to='user.address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EditorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editor_address', to='user.address')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to='user.address'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
