# Generated by Django 4.2.4 on 2023-08-16 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(choices=[('Seoul', '서울특별시'), ('Gyeonggi', '경기도'), ('Incheon', '인천광역시'), ('Gangwon', '강원도'), ('Chungbuk', '충청북도'), ('Chungnam', '충청남도'), ('Gyeongbuk', '경상북도'), ('Gyeongnam', '경상남도'), ('Jeju', '제주특별자치도'), ('Jeonbuk', '전라북도'), ('Jeonnam', '전라남도')], max_length=50)),
                ('city', models.CharField(blank=True, choices=[('Jungguo', '중구'), ('Jongrogu', '종로구'), ('Yongsangu', '용산구'), ('Seongdonggu', '성동구'), ('Gwangjingu', '광진구'), ('Dongdaemungu', '동대문구'), ('Jungranggu', '중랑구'), ('Seongbukgu', '성북구'), ('Gangbukgu', '강북구'), ('Dobonggu', '도봉구'), ('Nowongu', '노원구'), ('Eunpyeonggu', '은평구'), ('Seodaemungu', '서대문구'), ('Mapogu', '마포구'), ('Yangcheongu', '양천구'), ('Gangseogu', '강서구'), ('Gurogu', '구로구'), ('Geumcheongu', '금천구'), ('Uijeongbu', '의정부시'), ('Goyang', '고양시'), ('Yangju', '양주시'), ('Dongducheon', '동두천시'), ('Guri', '구리시'), ('Namyangju', '남양주시'), ('Paju', '파주시')], max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='editorprofile',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editor_address', to='user.address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_address', to='user.address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to='user.address'),
        ),
    ]
