# Generated by Django 4.1.7 on 2023-08-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_editorprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorprofile',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
