# Generated by Django 4.1.7 on 2023-08-18 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_editorprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editorprofile',
            name='name',
        ),
    ]
