# Generated by Django 4.1.7 on 2023-08-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_editorprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorprofile',
            name='editor_author',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
