# Generated by Django 4.1.7 on 2023-08-18 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_editorprofile_editor_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorprofile',
            name='user_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editor_profile_user_ID', to=settings.AUTH_USER_MODEL),
        ),
    ]
