# Generated by Django 4.1.7 on 2023-08-18 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_profile_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_ID',
        ),
    ]
